// ADD THIS FUNCTION TO CHECK IF TICKETS ALREADY EXIST


// REPLACE THE verifyPayment FUNCTION WITH THIS


// REPLACE generateMissingTickets FUNCTION WITH THIS


// REPLACE openPaymentModal FUNCTION WITH THIS ENHANCED VERSION


